version: "3.3"

services:
  chefwildcat-bot:
    container_name: chefwildcat
    image: 'chefwildcat/chefwildcatbot'
    build:
      context: ./chefwildcat-bot/
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3001:3001
    environment: 
      - EXTERNAL_PORT=3001
      - PGUSER=admin
      - PGPASSWORD=12345
      - PGDATABASE=defaultdb
      - PGHOST=pgdb
    depends_on:
      - pgdb
  webpage:
    container_name: webpage
    image: 'chefwildcat/chefwildcatwebpage'
    build:
      context: ./
      dockerfile: ./webpage/Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3003:3003
    environment: 
      - EXTERNAL_PORT=3003
      - PGUSER=admin
      - PGPASSWORD=12345
      - PGDATABASE=defaultdb
      - PGHOST=pgdb
    depends_on:
      - pgdb
      - chefwildcat-bot
  pgdb: 
    container_name: pgdb
    image: 'postgres:12'
    ports: 
      - 3002:3002
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=defaultdb
    volumes:
      - pgdata1:/var/lib/postgresql/data
    
volumes:
  pgdata1: {}